### PR TITLE
Adding Tests

### PR DESCRIPTION
**Pull request by mehradsadeghi**
Making up testing environment and writing unit tests for `validateCredentialsTrait`.

### CODE REVIEW

**Comment by imanghafoori1** [comment]
Models should also reside in the tests directory.

**Comment by mehradsadeghi** [comment]
> Models should reside in the **stubs** directory.

Done.

**Comment by imanghafoori1** [comment]
Tell me if this PR is ready to be merged.

**Comment by mehradsadeghi** [comment]
> Tell me if this PR is ready to be merged.

It's ready.

**Pull request merged**
