### PR TITLE
Add support for laravel 8

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by imanghafoori1** [comment]
Nice, Have you tested this with L8 ?

**Comment by lloricode** [comment]
thanks @imanghafoori1,

I already read the upgrade guide to laravel 8, seems there is no deprecate that affect in your library, since you library focus in authentication, and no deprecate athentication mention in documentation upgrade guide to laravel 8

**Comment by lloricode** [comment]
@imanghafoori1 can you tag this update?

**Comment by imanghafoori1** [comment]
tagged

**Pull request merged**
